[placeholders]
windows = { type = "bool", prompt = "Use windows syntax?", default = false }

[conditional.'windows'.placeholders]
win_start={ type = "string", default = "$env" }
win_quote={ type = "string", default = "\"" }
